apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLOUDFLARE_API_TOKEN
              value: {{ .Values.secrets.apiToken | b64dec }}
            - name: CLOUDFLARE_ZONE_ID
              value: {{ .Values.secrets.zoneId | b64dec }}
            - name: TARGET_CNAME_ADDRESS
              value: {{ .Values.secrets.targetCnameAddress | b64dec }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
