apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.secrets.apiToken | b64enc | quote }}
  CLOUDFLARE_ZONE_ID: {{ .Values.secrets.zoneId | b64enc | quote }}
  TARGET_CNAME_ADDRESS: {{ .Values.secrets.targetCnameAddress | b64enc | quote }}
